/*
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_hris_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import merge_hris_client.model.ModelOperation;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountDetailsAndActionsIntegration
 */
public class AccountDetailsAndActionsIntegrationTest {
    private final AccountDetailsAndActionsIntegration model = new AccountDetailsAndActionsIntegration();

    /**
     * Model tests for AccountDetailsAndActionsIntegration
     */
    @Test
    public void testAccountDetailsAndActionsIntegration() {
        // TODO: test AccountDetailsAndActionsIntegration
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'squareImage'
     */
    @Test
    public void squareImageTest() {
        // TODO: test squareImage
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'passthroughAvailable'
     */
    @Test
    public void passthroughAvailableTest() {
        // TODO: test passthroughAvailable
    }

    /**
     * Test the property 'availableModelOperations'
     */
    @Test
    public void availableModelOperationsTest() {
        // TODO: test availableModelOperations
    }

}
