/*
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_hris_client.model;

import org.junit.Test;


/**
 * Model tests for Earning
 */
public class EarningTest {
    private final Earning model = new Earning();

    /**
     * Model tests for Earning
     */
    @Test
    public void testEarning() {
        // TODO: test Earning
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'employeePayrollRun'
     */
    @Test
    public void employeePayrollRunTest() {
        // TODO: test employeePayrollRun
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'remoteData'
     */
    @Test
    public void remoteDataTest() {
        // TODO: test remoteData
    }

}
