/*
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_hris_client.model;

import org.junit.Test;


/**
 * Model tests for EmploymentRequest
 */
public class EmploymentRequestTest {
    private final EmploymentRequest model = new EmploymentRequest();

    /**
     * Model tests for EmploymentRequest
     */
    @Test
    public void testEmploymentRequest() {
        // TODO: test EmploymentRequest
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'payRate'
     */
    @Test
    public void payRateTest() {
        // TODO: test payRate
    }

    /**
     * Test the property 'payPeriod'
     */
    @Test
    public void payPeriodTest() {
        // TODO: test payPeriod
    }

    /**
     * Test the property 'payFrequency'
     */
    @Test
    public void payFrequencyTest() {
        // TODO: test payFrequency
    }

    /**
     * Test the property 'payCurrency'
     */
    @Test
    public void payCurrencyTest() {
        // TODO: test payCurrency
    }

    /**
     * Test the property 'flsaStatus'
     */
    @Test
    public void flsaStatusTest() {
        // TODO: test flsaStatus
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'employmentType'
     */
    @Test
    public void employmentTypeTest() {
        // TODO: test employmentType
    }

}
