/*
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_hris_client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ReasonEnum
 */
public class ReasonEnumTest {
    /**
     * Model tests for ReasonEnum
     */
    @Test
    public void testReasonEnum() {
        // TODO: test ReasonEnum
    }

}
