/*
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_hris_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import merge_hris_client.model.EmploymentTypeEnum;
import merge_hris_client.model.FlsaStatusEnum;
import merge_hris_client.model.PayCurrencyEnum;
import merge_hris_client.model.PayFrequencyEnum;
import merge_hris_client.model.PayPeriodEnum;
import merge_hris_client.model.RemoteData;
import org.threeten.bp.OffsetDateTime;

/**
 * # The Employment Object ### Description The &#x60;Employment&#x60; object is used to represent an employment position at a company. These are associated with the employee filling the role.  Please note: Employment objects are constructed if the object does not exist in the remote system.  ### Usage Example Fetch from the &#x60;LIST Employments&#x60; endpoint and filter by &#x60;ID&#x60; to show all employees.
 */
@ApiModel(description = "# The Employment Object ### Description The `Employment` object is used to represent an employment position at a company. These are associated with the employee filling the role.  Please note: Employment objects are constructed if the object does not exist in the remote system.  ### Usage Example Fetch from the `LIST Employments` endpoint and filter by `ID` to show all employees.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-12T20:57:27.935941Z[Etc/UTC]")
public class Employment {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_REMOTE_ID = "remote_id";
  @SerializedName(SERIALIZED_NAME_REMOTE_ID)
  private String remoteId;

  public static final String SERIALIZED_NAME_EMPLOYEE = "employee";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE)
  private UUID employee;

  public static final String SERIALIZED_NAME_JOB_TITLE = "job_title";
  @SerializedName(SERIALIZED_NAME_JOB_TITLE)
  private String jobTitle;

  public static final String SERIALIZED_NAME_PAY_RATE = "pay_rate";
  @SerializedName(SERIALIZED_NAME_PAY_RATE)
  private Float payRate;

  public static final String SERIALIZED_NAME_PAY_PERIOD = "pay_period";
  @SerializedName(SERIALIZED_NAME_PAY_PERIOD)
  private PayPeriodEnum payPeriod;

  public static final String SERIALIZED_NAME_PAY_FREQUENCY = "pay_frequency";
  @SerializedName(SERIALIZED_NAME_PAY_FREQUENCY)
  private PayFrequencyEnum payFrequency;

  public static final String SERIALIZED_NAME_PAY_CURRENCY = "pay_currency";
  @SerializedName(SERIALIZED_NAME_PAY_CURRENCY)
  private PayCurrencyEnum payCurrency;

  public static final String SERIALIZED_NAME_PAY_GROUP = "pay_group";
  @SerializedName(SERIALIZED_NAME_PAY_GROUP)
  private UUID payGroup;

  public static final String SERIALIZED_NAME_FLSA_STATUS = "flsa_status";
  @SerializedName(SERIALIZED_NAME_FLSA_STATUS)
  private FlsaStatusEnum flsaStatus;

  public static final String SERIALIZED_NAME_EFFECTIVE_DATE = "effective_date";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_DATE)
  private OffsetDateTime effectiveDate;

  public static final String SERIALIZED_NAME_EMPLOYMENT_TYPE = "employment_type";
  @SerializedName(SERIALIZED_NAME_EMPLOYMENT_TYPE)
  private EmploymentTypeEnum employmentType;

  public static final String SERIALIZED_NAME_REMOTE_DATA = "remote_data";
  @SerializedName(SERIALIZED_NAME_REMOTE_DATA)
  private List<RemoteData> remoteData = null;

  public static final String SERIALIZED_NAME_REMOTE_WAS_DELETED = "remote_was_deleted";
  @SerializedName(SERIALIZED_NAME_REMOTE_WAS_DELETED)
  private Boolean remoteWasDeleted;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "65d8ffd0-211b-4ba4-b85a-fbe2ce220982", value = "")

  public UUID getId() {
    return id;
  }




  public Employment remoteId(String remoteId) {
    
    this.remoteId = remoteId;
    return this;
  }

   /**
   * The third-party API ID of the matching object.
   * @return remoteId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "19202938", value = "The third-party API ID of the matching object.")

  public String getRemoteId() {
    return remoteId;
  }


  public void setRemoteId(String remoteId) {
    this.remoteId = remoteId;
  }


  public Employment employee(UUID employee) {
    
    this.employee = employee;
    return this;
  }

   /**
   * Get employee
   * @return employee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0958cbc6-6040-430a-848e-aafacbadf4ae", value = "")

  public UUID getEmployee() {
    return employee;
  }


  public void setEmployee(UUID employee) {
    this.employee = employee;
  }


  public Employment jobTitle(String jobTitle) {
    
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * The position&#39;s title.
   * @return jobTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Executive Assistant to Tom Wambsgans", value = "The position's title.")

  public String getJobTitle() {
    return jobTitle;
  }


  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }


  public Employment payRate(Float payRate) {
    
    this.payRate = payRate;
    return this;
  }

   /**
   * The position&#39;s pay rate in dollars.
   * @return payRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "50000.00", value = "The position's pay rate in dollars.")

  public Float getPayRate() {
    return payRate;
  }


  public void setPayRate(Float payRate) {
    this.payRate = payRate;
  }


  public Employment payPeriod(PayPeriodEnum payPeriod) {
    
    this.payPeriod = payPeriod;
    return this;
  }

   /**
   * The time period this pay rate encompasses.
   * @return payPeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "YEAR", value = "The time period this pay rate encompasses.")

  public PayPeriodEnum getPayPeriod() {
    return payPeriod;
  }


  public void setPayPeriod(PayPeriodEnum payPeriod) {
    this.payPeriod = payPeriod;
  }


  public Employment payFrequency(PayFrequencyEnum payFrequency) {
    
    this.payFrequency = payFrequency;
    return this;
  }

   /**
   * The position&#39;s pay frequency.
   * @return payFrequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "BIWEEKLY", value = "The position's pay frequency.")

  public PayFrequencyEnum getPayFrequency() {
    return payFrequency;
  }


  public void setPayFrequency(PayFrequencyEnum payFrequency) {
    this.payFrequency = payFrequency;
  }


  public Employment payCurrency(PayCurrencyEnum payCurrency) {
    
    this.payCurrency = payCurrency;
    return this;
  }

   /**
   * The position&#39;s currency code.
   * @return payCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "USD", value = "The position's currency code.")

  public PayCurrencyEnum getPayCurrency() {
    return payCurrency;
  }


  public void setPayCurrency(PayCurrencyEnum payCurrency) {
    this.payCurrency = payCurrency;
  }


  public Employment payGroup(UUID payGroup) {
    
    this.payGroup = payGroup;
    return this;
  }

   /**
   * Get payGroup
   * @return payGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "d4e4837f-9900-484c-ac40-528365bb08ef", value = "")

  public UUID getPayGroup() {
    return payGroup;
  }


  public void setPayGroup(UUID payGroup) {
    this.payGroup = payGroup;
  }


  public Employment flsaStatus(FlsaStatusEnum flsaStatus) {
    
    this.flsaStatus = flsaStatus;
    return this;
  }

   /**
   * The position&#39;s FLSA status.
   * @return flsaStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "EXEMPT", value = "The position's FLSA status.")

  public FlsaStatusEnum getFlsaStatus() {
    return flsaStatus;
  }


  public void setFlsaStatus(FlsaStatusEnum flsaStatus) {
    this.flsaStatus = flsaStatus;
  }


  public Employment effectiveDate(OffsetDateTime effectiveDate) {
    
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * The position&#39;s effective date.
   * @return effectiveDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-10-06T18:42:34Z", value = "The position's effective date.")

  public OffsetDateTime getEffectiveDate() {
    return effectiveDate;
  }


  public void setEffectiveDate(OffsetDateTime effectiveDate) {
    this.effectiveDate = effectiveDate;
  }


  public Employment employmentType(EmploymentTypeEnum employmentType) {
    
    this.employmentType = employmentType;
    return this;
  }

   /**
   * The position&#39;s type of employment.
   * @return employmentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FULL TIME", value = "The position's type of employment.")

  public EmploymentTypeEnum getEmploymentType() {
    return employmentType;
  }


  public void setEmploymentType(EmploymentTypeEnum employmentType) {
    this.employmentType = employmentType;
  }


   /**
   * Get remoteData
   * @return remoteData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{\"path\":\"/jobs\",\"data\":[\"Varies by platform\"]}]", value = "")

  public List<RemoteData> getRemoteData() {
    return remoteData;
  }




   /**
   * Indicates whether or not this object has been deleted on the third-party.
   * @return remoteWasDeleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether or not this object has been deleted on the third-party.")

  public Boolean getRemoteWasDeleted() {
    return remoteWasDeleted;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Employment employment = (Employment) o;
    return Objects.equals(this.id, employment.id) &&
        Objects.equals(this.remoteId, employment.remoteId) &&
        Objects.equals(this.employee, employment.employee) &&
        Objects.equals(this.jobTitle, employment.jobTitle) &&
        Objects.equals(this.payRate, employment.payRate) &&
        Objects.equals(this.payPeriod, employment.payPeriod) &&
        Objects.equals(this.payFrequency, employment.payFrequency) &&
        Objects.equals(this.payCurrency, employment.payCurrency) &&
        Objects.equals(this.payGroup, employment.payGroup) &&
        Objects.equals(this.flsaStatus, employment.flsaStatus) &&
        Objects.equals(this.effectiveDate, employment.effectiveDate) &&
        Objects.equals(this.employmentType, employment.employmentType) &&
        Objects.equals(this.remoteData, employment.remoteData) &&
        Objects.equals(this.remoteWasDeleted, employment.remoteWasDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, remoteId, employee, jobTitle, payRate, payPeriod, payFrequency, payCurrency, payGroup, flsaStatus, effectiveDate, employmentType, remoteData, remoteWasDeleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Employment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    remoteId: ").append(toIndentedString(remoteId)).append("\n");
    sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("    payRate: ").append(toIndentedString(payRate)).append("\n");
    sb.append("    payPeriod: ").append(toIndentedString(payPeriod)).append("\n");
    sb.append("    payFrequency: ").append(toIndentedString(payFrequency)).append("\n");
    sb.append("    payCurrency: ").append(toIndentedString(payCurrency)).append("\n");
    sb.append("    payGroup: ").append(toIndentedString(payGroup)).append("\n");
    sb.append("    flsaStatus: ").append(toIndentedString(flsaStatus)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    employmentType: ").append(toIndentedString(employmentType)).append("\n");
    sb.append("    remoteData: ").append(toIndentedString(remoteData)).append("\n");
    sb.append("    remoteWasDeleted: ").append(toIndentedString(remoteWasDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

