
/*
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package merge_hris_client.model;

import java.util.Objects;

import com.google.gson.JsonElement;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import merge_hris_client.JSON;
import org.threeten.bp.OffsetDateTime;

/**
 * MetaResponseRawJson
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-12T20:57:27.935941Z[Etc/UTC]")
public class MetaResponseRawJson {
  public static final String SERIALIZED_NAME_REQUEST_SCHEMA = "request_schema";
  @SerializedName(SERIALIZED_NAME_REQUEST_SCHEMA)
  private JsonElement requestSchema;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private JsonElement status;

  public static final String SERIALIZED_NAME_HAS_CONDITIONAL_PARAMS = "has_conditional_params";
  @SerializedName(SERIALIZED_NAME_HAS_CONDITIONAL_PARAMS)
  private JsonElement hasConditionalParams;

  public static final String SERIALIZED_NAME_HAS_REQUIRED_LINKED_ACCOUNT_PARAMS = "has_required_linked_account_params";
  @SerializedName(SERIALIZED_NAME_HAS_REQUIRED_LINKED_ACCOUNT_PARAMS)
  private JsonElement hasRequiredLinkedAccountParams;

  private transient JSON serializer;

  public MetaResponseRawJson(JSON srlzer) { 
    
    this.serializer = srlzer;
  }

  public MetaResponseRawJson requestSchema(Map<String, Object> requestSchema) {
    this.requestSchema = this.serializer.getGson().toJsonTree(requestSchema);
    return this;
  }

   /**
   * Get requestSchema
   * @return requestSchema
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public JsonElement getRequestSchema() {
    return requestSchema;
  }
  public void setRequestSchema(JsonElement requestSchema) {
    this.requestSchema = requestSchema;
  }

  public MetaResponseRawJson status(LinkedAccountStatus status) {
    this.status = this.serializer.getGson().toJsonTree(status);
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JsonElement getStatus() {
    return status;
  }
  public void setStatus(JsonElement status) {
    this.status = status;
  }

  public MetaResponseRawJson hasConditionalParams(Boolean hasConditionalParams) {
    this.hasConditionalParams = this.serializer.getGson().toJsonTree(hasConditionalParams);
    return this;
  }

   /**
   * Get hasConditionalParams
   * @return hasConditionalParams
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public JsonElement getHasConditionalParams() {
    return hasConditionalParams;
  }
  public void setHasConditionalParams(JsonElement hasConditionalParams) {
    this.hasConditionalParams = hasConditionalParams;
  }

  public MetaResponseRawJson hasRequiredLinkedAccountParams(Boolean hasRequiredLinkedAccountParams) {
    this.hasRequiredLinkedAccountParams = this.serializer.getGson().toJsonTree(hasRequiredLinkedAccountParams);
    return this;
  }

   /**
   * Get hasRequiredLinkedAccountParams
   * @return hasRequiredLinkedAccountParams
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public JsonElement getHasRequiredLinkedAccountParams() {
    return hasRequiredLinkedAccountParams;
  }
  public void setHasRequiredLinkedAccountParams(JsonElement hasRequiredLinkedAccountParams) {
    this.hasRequiredLinkedAccountParams = hasRequiredLinkedAccountParams;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetaResponseRawJson metaResponse = (MetaResponseRawJson) o;
    return Objects.equals(this.requestSchema.getAsString(), metaResponse.requestSchema.getAsString()) &&
        Objects.equals(this.status.getAsString(), metaResponse.status.getAsString()) &&
        Objects.equals(this.hasConditionalParams.getAsString(), metaResponse.hasConditionalParams.getAsString()) &&
        Objects.equals(this.hasRequiredLinkedAccountParams.getAsString(), metaResponse.hasRequiredLinkedAccountParams.getAsString());
  }
  @Override
  public int hashCode() {
    return Objects.hash(requestSchema, status, hasConditionalParams, hasRequiredLinkedAccountParams);
  }
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetaResponseRawJson {\n");
    sb.append("    requestSchema: ").append(toIndentedString(requestSchema.getAsString())).append("\n");
    sb.append("    status: ").append(toIndentedString(status.getAsString())).append("\n");
    sb.append("    hasConditionalParams: ").append(toIndentedString(hasConditionalParams.getAsString())).append("\n");
    sb.append("    hasRequiredLinkedAccountParams: ").append(toIndentedString(hasRequiredLinkedAccountParams.getAsString())).append("\n");
    sb.append("}");
    return sb.toString();
  }
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}


