/*
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package java.merge_hris_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.merge_hris_client.model.CategoryEnum;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountDetails
 */
public class AccountDetailsTest {
    private final AccountDetails model = new AccountDetails();

    /**
     * Model tests for AccountDetails
     */
    @Test
    public void testAccountDetails() {
        // TODO: test AccountDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'integration'
     */
    @Test
    public void integrationTest() {
        // TODO: test integration
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'endUserOriginId'
     */
    @Test
    public void endUserOriginIdTest() {
        // TODO: test endUserOriginId
    }

    /**
     * Test the property 'endUserOrganizationName'
     */
    @Test
    public void endUserOrganizationNameTest() {
        // TODO: test endUserOrganizationName
    }

    /**
     * Test the property 'endUserEmailAddress'
     */
    @Test
    public void endUserEmailAddressTest() {
        // TODO: test endUserEmailAddress
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
